### ISSUE TITLE
Revert wasn't quite complete

### ISSUE THREAD

**Issue by clydemcqueen** [apl-ocean-engineering/vc-jetson-driver-release#3]
I looks like you need to remove this line as well... otherwise the child Makefiles install the various artifacts into the `install/boot` directory relative to the child Makefile directory, and `vc-jetson-driver-release/install` is left empty.

https://github.com/apl-ocean-engineering/vc-jetson-driver-release/blob/8a51048beca39f02a83f3ba569afdf820446227b/Makefile#L14C1-L14C28

**Comment by clydemcqueen** [comment]
Shoot, that isn't correct either, the archive paths are wrong:

~~~
clyde@fastr2:~/projects/vc-jetson-driver-release (l4t-36.4.0/alpha *)$ tar tvf install.tar.bz2 
drwxrwxr-x clyde/clyde       0 2024-11-01 17:32 home/clyde/projects/vc-jetson-driver-release/install/
drwxrwxr-x clyde/clyde       0 2024-11-01 17:32 home/clyde/projects/vc-jetson-driver-release/install/boot/
-rw-r--r-- clyde/clyde    7547 2024-11-01 17:32 home/clyde/projects/vc-jetson-driver-release/install/boot/tegra234-p3767-camera-p3768-vc_mipi-dual-imx.dtbo
~~~

**Comment by amarburg** [comment]
Yeah, I thought I could eliminate `setup.sh` ... essentially go for convention over configuration.   But it sounds like passing environment variables from a parent Makefile to a subshell Makefile is hard. 

5ca56ae rolls that back, re-institutes `setup.sh`, but adds a check for the existence of the env variables in Makefile.

Also added some improved path mangling when making the tarfile.
